### ISSUE TITLE
Porting to FF to a custom SPI platform

### ISSUE THREAD

**Issue by dikdom** [feilipu/z88dk-libraries#2]
Hello,

what is the relation with these FF packages and the sdcard in the std z88dk package? Do I see it properly, that ff is built on diskio and diskio is built on sdcard (in case of scz180)?

I'm planning to implement (port?) the FF package to an 8bit (z80 based) computer having an uSD socket. The communication shall be based on sw SPI. Is there any doc/guidelines about it?

For the sdcard in z88dk I guess only a few methods should be implemented, but that doesn't provide a file (FAT12/16/32) support, just raw device access, if I'm not mistaken.

But for the FF lib I'm afraid I need to implement a brand new diskio_sd... Or ? ...

I'm not sure that it would even fit into my 3x16kB ROM ...

Thanks!

**Comment by feilipu** [comment]
Hi @dikdom,

> What is the relation with these FF packages and the sdcard in the std z88dk package?

The FatFS (or ff) package is almost purely the ChaN FatFs library. ChaN has been very strict in his coding of a layered system, using only C89 construction. This makes it an ideal implementation of the Microsoft FAT for z80 (and all other small systems).

It is worthwhile to [have a good look at his documentation](http://elm-chan.org/fsw/ff/00index_e.html), both copied here and the original on his web site. There he speaks about how to implement and use FatFs and provides many examples for testing, etc.

> Do I see it properly, that ff is built on diskio and diskio is built on sdcard (in case of scz180)?

The disk interface for FatFS is called diskio. The diskio code only has to provide a number of simple functions to the FatFs library, and that makes it super easy to implement FatFs and test on a new disk hardware.

I've built a diskio for a couple of different machines. In every case it is providing the same functions to FatFs.

scz180 - based on a SD card  - [in this repository](https://github.com/feilipu/z88dk-libraries/blob/master/diskio_sd/source/diskio_sd.c)
scz180 - based on HBIOS calls - [in this repository](https://github.com/feilipu/z88dk-libraries/blob/master/diskio_hbios/source/diskio_hbios.c)
yaz180 - based on integrated 8255 PPI hardware - in the [z88dk drivers for this target](https://github.com/z88dk/z88dk/tree/master/libsrc/_DEVELOPMENT/target/yaz180/driver/diskio)
rc2014 - based on the 8255 PPI CF Module - in the [z88dk drivers for this target](https://github.com/z88dk/z88dk/tree/master/libsrc/_DEVELOPMENT/target/rc2014/driver/diskio)
rc2014 - based on the 8-bit compatibility mode CF Module - in the [z88dk drivers for this target](https://github.com/z88dk/z88dk/tree/master/libsrc/_DEVELOPMENT/target/rc2014/driver/diskio)

The SD implementations of diskio are quite finicky. The SD card requires the right number of (for example) null bytes to be sent in specific instances. Even today Wayne [tweaks the RomWBW `sd.asm`](https://github.com/wwarthen/RomWBW/issues/352) code to improve it. Having said that I'm quite confident about the scz180 SD code, and I've used it also for ATmega SPI interfaces extensively too. The SD code can be used as it stands.

> For the sdcard in z88dk I guess only a few methods should be implemented, but that doesn't provide a file (FAT12/16/32) support, just raw device access, if I'm not mistaken.

Yes. The underlying physical interfaces to the SD card for the scz180 are in the [z88dk CISO device for this target](https://github.com/z88dk/z88dk/tree/master/libsrc/_DEVELOPMENT/target/scz180/device/csio). This is the minimum set required to access the physical SD card using the CISO interface on the z180. For your hardware it will probably be a shift register solution of some type, which will need specific controls of its own.

> But for the FF lib I'm afraid I need to implement a brand new diskio_sd... Or ? ...

If you have a different physical interface you will need to change these few I/O routines to suit your hardware.

You just need to read/write a byte and read/write a block of 512 bytes. It is also useful to separately control the CS pin as this is needed sometimes. And, if you are lazy, reading a block is just reading a byte 512 times, though the `djnz` instruction lends itself for reading a block two bytes at a time.

> I'm not sure that it would even fit into my 3x16kB ROM ...

For the RC2014, I use the FatFs library with the 8255 PPI drivers or the 8-bit CF compatibility drivers together with all of CP/M and a shell written in C all within 32kB. To do this I have to build a read only version of the library. The [configuration for this](https://github.com/feilipu/z88dk-libraries/blob/master/ff/source/ffconf.h#L12) is one of the small adjustments I've made to the FatFS library. `#define FF_FS_READONLY  1`. So I don't think you'll have any problem.

The other small adjustment is to use [direct access for 8 bit load and store](https://github.com/feilipu/z88dk-libraries/blob/master/ff/source/ff.c#L53) to optimise the FatFs access to information. Otherwise using a function would cause a lot of overhead.

Hope this helps.

**Comment by dikdom** [comment]
Sure, it does, thanks for your detailed reply!

So, if I'm not mistaken a crude approach would be to reuse SD based diskio implementation and adjust scz180's low level SPI implementation - for my needs. 

The diskio requires that the following methods be implemented: 
`
__DPROTO(`iyh,iyl',`iyh,iyl',DSTATUS,,disk_initialize,BYTE pdrv)
__DPROTO(`iyh,iyl',`iyh,iyl',DSTATUS,,disk_status,BYTE pdrv)
__OPROTO(`iyh,iyl',`iyh,iyl',DRESULT,,disk_read,BYTE pdrv, BYTE* buff, LBA_t sector, UINT count)
__OPROTO(`iyh,iyl',`iyh,iyl',DRESULT,,disk_write,BYTE pdrv, const BYTE* buff, LBA_t sector, UINT count)
__OPROTO(`iyh,iyl',`iyh,iyl',DRESULT,,disk_ioctl,BYTE pdrv, BYTE cmd, void* buff)
`
(initialize, disk_status, disk_read, disk_write, disk_ioctl) if I understand properly.

**Comment by feilipu** [comment]
> So, if I'm not mistaken a crude approach would be to reuse SD based diskio implementation and adjust scz180's low level SPI implementation - for my needs.

Not crude at all. This is the most robust way to do it. IMHO my SD `diskio` implementation is pretty well tuned, and in C the z88dk compilers can build it for any z80/8080 variant. It does all the `diskio` functions for you with no effort.

Your concern will be reading and writing to the SPI hardware, just 4 IO routines.

Once they're done, you can move to testing at diskio level quickly, and then the FatFs library drops on top.

**Comment by dikdom** [comment]
okay.. So what I did I created a source file that contains the implementation of the following methods:
```
void sd_cs_raise(void);
void sd_cs_lower(int a);
char sd_read_byte(void);
void sd_write_byte(char b);
void sd_clock(uint8_t c);
uint32_t hbios(uint16_t ctl);
```
(not just their header). Created a main.c having some dummy ff operations in its main() method. Ok. 
I compiled with `zcc` using the `+zx81` target selector and I got a nice binary file. Probably wouldn't run, but now it is not that interesting. I guess this is what you suggested.


Unfortunately I cannot stay with the z88dk compiler because I have a large part of my project already created for sjasm. 
So I made the `zcc` to create and leave the .asm files. Ok. In the ff.c.asm file there is reference to `l_long_ne` (i believe to `libsrc\_DEVELOPMENT\l\sccz80\5-z80\i32\l_long_ne.asm` ) and that is confusing to me. The ZX81 uses the IX register for display routine, so that register must not be changed but the first operation of the `l_long_ne` routine is `pop IX`..
I guess this is a bug of the compiler but how could I report this?
This is how I created the .asm files:
`zcc +zx81 -Csclib=new -v --list -O2 --opt-code-speed=add32,sub32,sub16,inlineints --math32 -D__SDANDJOY_ZX81 @sdandjoy.lst -o sdandjoy -create-app`
Do I miss here something?

**Comment by feilipu** [comment]
> This is how I created the .asm files:
`zcc +zx81 -C -clib=new -v --list -O2 --opt-code-speed=add32,sub32,sub16,inlineints --math32 -D__SDANDJOY_ZX81 @sdandjoy.lst -o sdandjoy -create-app`
Do I miss here something?

Yes, you've just missed one small thing. Because there are different machines needing to use different index registers in different way, the libraries are always written with use of one index register `IX`. If the compiler uses `IX` like `zsdcc` or if the machine needs `IX`, then the library index register is swapped during linking to be `IY`. You can see this in the configuration for the ZX81, [here](https://github.com/z88dk/z88dk/blob/master/lib/config/zx81.cfg#L16) where the `-mz80_ixiy` and `clibs/ixiy` appears.

```asm
# Any default options you want - these are options to zcc which are fed
# through to compiler, assembler etc as necessary
OPTIONS		 -O2 -SO2 -iquote. -mz80_ixiy -Cc-standard-escape-chars -DZ80 -DZX81 -D__ZX81__ -M -subtype=default -clib=default -Cs--reserve-regs-iy -Ca-IDESTDIR/lib/target/zx81/def  -Cz+zx81 -IDESTDIR/include/arch/zx81  -LDESTDIR/lib/clibs/ixiy
```
That's why the preferred `zsdcc` builds always use `--reserve-regs-iy`, so that the library has unrestricted use of `IY` in `sdcc_iy` libraries and the compiler has use of `IX`. Even though it looks like the libraries are written to use `IX`...! Though there is also the `sdcc_ix` version that shares the use of `IX`.

**Comment by dikdom** [comment]
Thanks!
So it means that the IX register usage is _silently_ replaced with IY usage during linking? Or is there any (temporary) source also created for that?
By the way. Is there a way to make the zcc compiler to show exactly what library methods are in use during compiling or linking the compiled source?

**Comment by feilipu** [comment]
> By the way. Is there a way to make the zcc compiler to show exactly what library methods are in use during compiling or linking the compiled source?

Yes. Use the map file `-m` which includes all the labels actually used, and where they are sourced from (i.e. which file).

This is getting to the limit of my knowledge. Perhaps @suborb could comment if he hears.
Otherwise raise a question issue on z88dk/z88dk repo to ask.

**Comment by suborb** [comment]
> By the way. Is there a way to make the zcc compiler to show exactly what library methods are in use during compiling or linking the compiled source?

You can also add the option -Cl-v which will print the library routines to the console at link time. I generally find that more useful for indicative info than the .map file.

**Comment by dikdom** [comment]
Thanks for the answers!
In the meantime I got everything I wanted (I think). I was able to compile the generated ASM codes (with slight modifications) to my EEPROM and it runs in ZX81.
Just the init always returns $4000. Can be anything, I'm afraid. 

The link above is a mistake. I didn't know that writing a plain hashmark and a number in my new issue would create a reference to here. Edited, but here the back-reference remained...
